export const themes = {
    'mode-jour': {
      name: 'mode-jour',
      backgroundColor: '#eaf2fd',
      textColor: '#000',
      primary: '#a6d4ff',
      secondary: '#ebf5fa',
      cardBackground: '#ffffff',
      borderColor: '#ccc',
      buttonText: '#000',
      buttonBackground: '#a6d4ff',
      buttonHover: '#86c2f3',
      popupBackground: '#ffffff',
    },
    'mode-nuit': {
      name: 'mode-nuit',
      backgroundColor: '#0b0626',
      textColor: '#e0e0e0',
      primary: '#2a387f',
      secondary: '#171a38',
      cardBackground: '#1f1f3d',
      borderColor: '#444',
      buttonText: '#ffffff',
      buttonBackground: '#2a387f',
      buttonHover: '#3c4b9f',
      popupBackground: '#1f1f3d',
    },
    'mode-zen': {
      name: 'mode-zen',
      backgroundColor: '#cfe4d9',
      textColor: '#1e1e1e',
      primary: '#77a08e',
      secondary: '#9cccb5',
      cardBackground: '#d8f0e4',
      borderColor: '#aacdbf',
      buttonText: '#1e1e1e',
      buttonBackground: '#77a08e',
      buttonHover: '#9cccb5',
      popupBackground: '#ffffff',
    },
    'mode-cyberpunk': {
      name: 'mode-cyberpunk',
      backgroundColor: '#1a1a40',
      textColor: '#ffffff',
      primary: '#ff00ff',
      secondary: '#3c096c',
      cardBackground: '#0f0f2d',
      borderColor: '#5a189a',
      buttonText: '#1a1a40',
      buttonBackground: '#00ffff',
      buttonHover: '#ff4d80',
      popupBackground: '#2a003f',
    },
    'mode-steampunk': {
      name: 'mode-steampunk',
      backgroundColor: '#5b4433',
      textColor: '#fff0d6',
      primary: '#c9a66b',
      secondary: '#3e2f2f',
      cardBackground: '#fcf4d9',
      borderColor: '#a17c5b',
      buttonText: '#3e2f2f',
      buttonBackground: '#c9a66b',
      buttonHover: '#a17c5b',
      popupBackground: '#fcf4d9',
    },
    'mode-space': {
      name: 'mode-space',
      backgroundColor: '#000014',
      textColor: '#e0e1dd',
      primary: '#778da9',
      secondary: '#1b263b',
      cardBackground: '#2b3e59',
      borderColor: '#415a77',
      buttonText: '#ffffff',
      buttonBackground: '#778da9',
      buttonHover: '#a3bce2',
      popupBackground: '#1b263b',
    },
    'mode-neon': {
      name: 'mode-neon',
      backgroundColor: '#1f0236',
      textColor: '#ffffff',
      primary: '#783578',
      secondary: '#3b0866',
      cardBackground: '#2a2a5a',
      borderColor: '#ff00ff',
      buttonText: '#ffffff',
      buttonBackground: '#783578',
      buttonHover: '#7058b6',
      popupBackground: '#2a2a5a',
    },
    'mode-vintage': {
      name: 'mode-vintage',
      backgroundColor: '#f5e9d3',
      textColor: '#4b3e2b',
      primary: '#e1c699',
      secondary: '#d4b483',
      cardBackground: '#fdf6e3',
      borderColor: '#c8a97e',
      buttonText: '#4b3e2b',
      buttonBackground: '#e1c699',
      buttonHover: '#d4b483',
      popupBackground: '#fdf6e3',
    },
    'mode-minimalist': {
      name: 'mode-minimalist',
      backgroundColor: '#ffffff',
      textColor: '#000',
      primary: '#dcdcdc',
      secondary: '#f7f7f7',
      cardBackground: '#f5f5f5',
      borderColor: '#e0e0e0',
      buttonText: '#000',
      buttonBackground: '#dcdcdc',
      buttonHover: '#bbbbbb',
      popupBackground: '#ffffff',
    },
  };
  
  export type ThemeType = keyof typeof themes;
  