export const themes = {
    'mode-jour': {
      name: 'mode-jour',
      backgroundColor: '#eaf2fd',
      textColor: '#000000',
      primary: '#a6d4ff',
      secondary: '#ebf5fa',
      cardBackground: '#ffffff',
      borderColor: '#ccc',
      buttonText: '#000000',
      buttonBackground: '#a6d4ff',
      popupBackground: '#ffffff',
    },
    'mode-nuit': {
      name: 'mode-nuit',
      backgroundColor: '#0b0626',
      textColor: '#e0e0e0',
      primary: '#2a387f',
      secondary: '#171a38',
      cardBackground: '#1f1f3d',
      borderColor: '#444',
      buttonText: '#ffffff',
      buttonBackground: '#2a387f',
      popupBackground: '#1f1f3d',
    },
    'mode-zen': {
      name: 'mode-zen',
      backgroundColor: '#cfe4d9',
      textColor: '#2e2e2e',
      primary: '#a8d5ba',
      secondary: '#e9f5f0',
      cardBackground: '#ffffff',
      borderColor: '#b3d9cc',
      buttonText: '#1b3b2f',
      buttonBackground: '#a8d5ba',
      popupBackground: '#ffffff',
    },
    'Cyberpunk': {
      name: 'Cyberpunk',
      backgroundColor: '#0f0f0f',
      textColor: '#f0f600',
      primary: '#ff00ff',
      secondary: '#00ffff',
      cardBackground: '#1e1e1e',
      borderColor: '#ff00ff',
      buttonText: '#000',
      buttonBackground: '#f0f600',
      popupBackground: '#121212',
    },
    'Steampunk': {
      name: 'Steampunk',
      backgroundColor: '#3b2f2f',
      textColor: '#f5deb3',
      primary: '#b87333',
      secondary: '#c0a16b',
      cardBackground: '#4a3a2e',
      borderColor: '#8b5a2b',
      buttonText: '#fff',
      buttonBackground: '#b87333',
      popupBackground: '#3b2f2f',
    },
    'Space': {
      name: 'Space',
      backgroundColor: '#0d0d2b',
      textColor: '#ffffff',
      primary: '#1e90ff',
      secondary: '#2e2e52',
      cardBackground: '#1a1a40',
      borderColor: '#333',
      buttonText: '#fff',
      buttonBackground: '#1e90ff',
      popupBackground: '#1a1a40',
    },
    'Neon Lights': {
      name: 'Neon Lights',
      backgroundColor: '#000000',
      textColor: '#39ff14',
      primary: '#ff073a',
      secondary: '#0ff0fc',
      cardBackground: '#121212',
      borderColor: '#333',
      buttonText: '#39ff14',
      buttonBackground: '#ff073a',
      popupBackground: '#000000',
    },
    'Vintage': {
      name: 'Vintage',
      backgroundColor: '#f5f5dc',
      textColor: '#5a4a42',
      primary: '#d2b48c',
      secondary: '#deb887',
      cardBackground: '#fffaf0',
      borderColor: '#a0522d',
      buttonText: '#5a4a42',
      buttonBackground: '#d2b48c',
      popupBackground: '#fffaf0',
    },
    'Minimalist': {
      name: 'Minimalist',
      backgroundColor: '#ffffff',
      textColor: '#333333',
      primary: '#d3d3d3',
      secondary: '#f5f5f5',
      cardBackground: '#ffffff',
      borderColor: '#e0e0e0',
      buttonText: '#333333',
      buttonBackground: '#d3d3d3',
      popupBackground: '#ffffff',
    }
  };
  